Rename export your project from version control
OpenFn/Lightning pull request #1019
Opened 2023-08-10 08:10 UTC by zacck

## Notes for the reviewer
Simple UI change, changed wording on project settings/ setup page to `Export your project` rather than version control as we are introducing a new version control feature

## Related issue

Fixes #1015 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [x] Product has **QA'd** this feature

2023-08-10 08:46 UTC, elias-ba approved these changes
Looks good to me

2023-08-10 15:04 UTC, stuartc requested changes
Please update the changelog, you marked it as done on the checklist.

2023-08-11 06:04 UTC, zacck commented
@stuartc the changelog has been updated, brings me to a segue, how do we determine what is big enough for a changelog is there something written somewhere

2023-08-14 08:35 UTC, stuartc approved these changes

2023-08-14 08:38 UTC, merged