Update Delete to Delete Job and Add Confirmation
OpenFn/Lightning pull request #1230
Opened 2023-10-23 10:29 UTC by benedictus-dev

## Notes for the reviewer
This PR changes the delete text to **Delete Job** on the button and adds a confirmation to delete

## Related issue

Fixes #1105 

## Review checklist

- [ ] I have performed a **self-review** of my code
- [ ] I have verified that all appropriate **authorization policies** have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

2023-10-23 10:45 UTC, elias-ba requested changes
Hey @benedictus-dev this looks great, congratulations. I have asked @NickOpenFn to give you the right message for the confirmation box. Remember that you need @NickOpenFn to approve the PR (UI) before we can merge this.

2023-10-23 10:45 UTC, elias-ba commented on lib/lightning_web/live/workflow_live/edit.ex
> +                        data-confirm="Are you sure?"
Hey @NickOpenFn what is the message for the confirmation box ?

2023-10-23 15:00 UTC, elias-ba commented
Hey @benedictus-dev this is looking good, thanks. @stuartc feel free to merge this anytime you can.

2023-10-25 07:41 UTC, stuartc approved these changes

2023-10-25 07:41 UTC, merged