895 move enabled disabled property from jobs to edges
OpenFn/Lightning pull request #1289
Opened 2023-11-07 06:25 UTC by benedictus-dev

## Notes for the reviewer

## Related issue
This PR addresses issue #895, focusing on the migration of the 'enabled/disabled' property from the 'jobs' to the 'edges' within our workflow management system
Fixes #

1. Introduces an 'enabled' boolean to edges, allowing for a more granular control over workflow 
2. Removes the 'enabled/disabled' toggles from the job panel, aligning with our strategy to separate the execution of jobs from decision-making processes.
## Review checklist

- [ ] I have performed a **self-review** of my code
- [ ] I have verified that all appropriate **authorization policies** have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

2023-11-07 07:14 UTC, taylordowns2000 requested changes
hey @benedictus-dev , looking good! please address all of my inline change requests. 

the big thing (workflow_params, line 16) is that upon disabling an edge all downstream edges are getting disabled. it looks super deliberate so i'm guessing this was simply a miscommunication somewhere. please make sure that when a user disables an edge, only that edge gets disabled. other elements of the workflow should be left alone.

2023-11-07 07:14 UTC, taylordowns2000 commented on lib/lightning/workflows/edge.ex
> +    field :enabled, :boolean
i think this should default to true to keep parity with the old `job.ex`

2023-11-07 07:14 UTC, taylordowns2000 commented on lib/lightning_web/live/workflow_live/edit.ex
> +    IO.puts("=====================When to trigger me ===============")
remove IO.inspect?

2023-11-07 07:14 UTC, taylordowns2000 commented on lib/lightning_web/live/workflow_live/workflow_params.ex
> +          if Map.has_key?(form_params, "edges") &&
i think this is the code that's setting downstream edges. please ensure that if someone disbales an edge, only that edge gets disabled.

2023-11-07 10:15 UTC, taylordowns2000 requested changes
1. please re-write these migrations to use a single migration that _moves_ the boolean from jobs to edges. this is fairly tricky. see details below.
2. please add tests (chat @midigofrank and @elias-ba on slack and rebase on release-0.10.0 once they've finished fixing the workflow params test.)

details on the migration:
- currently the enabled/disabled status lives on the jobs table.
- we need to determine what edge is pointing at each job, and _move_ the value of that boolean to the leading edge.
- the exception here is that no edges which lead from a trigger to a job may be disabled.

so to say it another way:
- first add the enabled column to edges
- then set the value with this logic:
  - if the edge has a `source_trigger_id`, set `edge.enabled = true`
  - if the edge does not have a source trigger, set the `edge.enabled` value to the `jobs.enabled` value for the `edge.target_job_id`
- then finally drop the `jobs.enabled` column

2023-11-09 17:03 UTC, taylordowns2000 requested changes
this works _great_ from a UX perspetive! nice job @benedictus-dev ! todo:

1. ~mark_for_deletion - is this doing what needs to be done? i thought we discussed setting the trigger to disabled.~ done
2. canonical_project - i see you've removed `enabled` from jobs. should i be added to edges?
3. `test/lightning/projects_test.exs` - i think this is related to number item 1. i think we discussed checking to see that triggers were disabled, rather than jobs.
4. `test/lightning/workflows/query_test.exs` - i'm not convinced that this enabled_cron_jobs_by_edge query is being tested properly with your changes. i'm also not sure it's being used anymore! how do we find a list of enabled cron workflows to create new attempts in the system?
5. see "impossible" comment on trigger-to-job edge with `enabled: false`. we should add validation here to stop this.
6. please remove remaining commented out code

2023-11-09 17:03 UTC, taylordowns2000 commented on test/lightning/workflows/query_test.exs
> +        enabled: false
this is impossible, i think!

2023-11-10 07:13 UTC, stuartc commented on test/lightning/workflows/query_test.exs
> +        workflow: _non_cron_job.workflow,
Variables prefixed with an underscore are a hint that the variable isn't supposed to be used: https://hexdocs.pm/elixir/main/naming-conventions.html#underscore-_foo

It was left there as a 'comment' of sorts, in tests they are permissible but we try and not have these kinds of variable names in the application code.

So in this situation, could you remove the `_` prefix from the variable.

2023-11-10 10:58 UTC, taylordowns2000 requested changes
looking really good @benedictus-dev . please address each of my final change requests and re-request a review. let's get this over the line!!!

2023-11-10 10:58 UTC, taylordowns2000 commented on lib/lightning/projects.ex
> +      workflows = project_workflows_query(project) |> Repo.all()
this should be `triggers`

2023-11-10 10:58 UTC, taylordowns2000 commented on lib/lightning/workflows/query.ex
> +      where: t.type == :cron and t.enabled and e.enabled,
remove `and e.enabled`

2023-11-10 10:58 UTC, taylordowns2000 commented on lib/lightning/projects.ex
> +        Lightning.Workflows.mark_for_deletion(workflow)
with this PR, you've moved `:enabled` from Jobs to Edges. On this line you should go from:
```
Lightning.Jobs.update_job(job, %{"enabled" => false})
```
to:
```
Lightning.Triggers.update_trigger(trigger, %{"enabled" => false})
```
There may not be an `update_trigger` function and you may need to make one or call `Repo.update()`

2023-11-10 10:58 UTC, taylordowns2000 commented on test/lightning/setup_utils_test.exs
> +      # assert job_3.enabled
remove commented code

2023-11-10 10:58 UTC, taylordowns2000 commented on test/lightning/setup_utils_test.exs
> +      # assert notify_upload_successful.enabled
remove commented code

2023-11-10 10:58 UTC, taylordowns2000 commented on test/lightning/workflows_test.exs
>        # Disabled Job
rename this comment; jobs can't be disabled

2023-11-10 12:35 UTC, taylordowns2000 approved these changes

2023-11-10 17:02 UTC, merged