Fix Incorrect Wording On The "Delete Job" Button Tooltip
OpenFn/Lightning pull request #1345
Opened 2023-11-10 02:12 UTC by elias-ba

## Notes for the reviewer

## Related issue

Fixes #1313 

## Review checklist

- [ ] I have performed a **self-review** of my code
- [ ] I have verified that all appropriate **authorization policies** have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

2023-11-21 13:24 UTC, taylordowns2000 requested changes
1. please move changelog entry into the existing "changes" section. (it's below the breaking change warning)
2. this isn't working for me. see loom: https://www.loom.com/share/3a0a88d61f5b41038edca418e9ea10f3

2023-11-22 09:24 UTC, stuartc approved these changes

2023-11-22 10:59 UTC, elias-ba commented
@stuartc as discussed this morning, I have tried to reproduce the problem in tests but I couldn't do so. I think with this new approach we will no longer be dealing with that problem. We assign in the `apply_action` the count for the number of jobs in the workflow. Which is different than dealing with the URL params for the selected node. So I think you can merge this and we deal with the initial problem later.

2023-11-22 14:00 UTC, stuartc approved these changes

2023-11-23 06:28 UTC, merged