940 workflow diagram order children consistently
OpenFn/Lightning pull request #1406
Opened 2023-11-20 03:49 UTC by benedictus-dev

## Notes for the reviewer
1, I have updated the timestamp precision in the Job schema to **:naive_datetime_usec** .
2, This was necessary to ensure a stable order of child nodes in the workflow diagram, as the default second-level precision was not sufficient for jobs created or updated close together in time.
3,I ran some tests, and things look good on my end – the nodes stay put now. But, you know, another pair of eyes is always great.

## Related issue
This PR addresses the issue where the order of child nodes in the workflow diagram varied randomly upon page refresh, especially after performing update operations on the node names. This inconsistency in ordering was particularly noticeable and problematic when the names of the nodes were changed.

Fixes #940 

## Review checklist

- [ ] I have performed a **self-review** of my code
- [ ] I have verified that all appropriate **authorization policies** have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

2023-11-20 09:13 UTC, josephjclark commented
I can't comment on the implementation but this looks like a good solution to me!

2023-11-20 11:47 UTC, stuartc requested changes
Functionally looks good! I see some merge conflicts, please rebase and fix them; and I've left a comment on the `jobs_ordered_subquery` function.

2023-11-20 11:47 UTC, stuartc commented on lib/lightning_web/live/workflow_live/edit.ex
> +            jobs: Workflows.jobs_ordered_subquery()
I don't think we should be moving the preload of the Jobs credential into a function that given it's name says it's just for ordering.

Anyone using that function may or may not expect credentials to be preloaded.

I would suggest one of the following:

1) Setting the `:preload_order` on the `has_many` of the Workflow model. See [here](https://hexdocs.pm/ecto/Ecto.Schema.html#has_many/3-options)
2) Extend the returned query from `jobs_ordered_subquery` with a `preload(:credential)`, that will keep the credential preload out of that function.
3) Don't add a function, and have it all inline here. And we refactor/abstract these queries later.

2023-11-22 13:49 UTC, stuartc approved these changes
Nice! Really like the `{query, [:more_preload]}` very clean.

2023-11-22 13:50 UTC, merged