Add match js option and related inputs
OpenFn/Lightning pull request #1547
Opened 2023-12-07 18:26 UTC by jyeshe

## Notes for the reviewer

## Related issue

Solves #1498

## Review checklist

- [ ] I have performed a **self-review** of my code
- [ ] I have verified that all appropriate **authorization policies** have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

2023-12-13 03:29 UTC, taylordowns2000 requested changes
hey @jyeshe , i'm seeing at least two things here that aren't quite right:
1. i'm not able to modify the edge between a trigger and a job. the options there should be always and the new custom js option.
2. after adding my custom condition, it disappears. (both the label and the input box.) and i'm unable to access it again.

https://www.loom.com/share/edd41b08c7a745849e9dff56e3dc8ba9

finally, please rebase this on `main` as i think it's a bit out of date and a rebase will make testing easier

2023-12-13 11:16 UTC, jyeshe commented
> hey @jyeshe , i'm seeing at least two things here that aren't quite right:
> 
> 1. i'm not able to modify the edge between a trigger and a job. the options there should be always and the new custom js option.
> 2. after adding my custom condition, it disappears. (both the label and the input box.) and i'm unable to access it again.
> 
> https://www.loom.com/share/edd41b08c7a745849e9dff56e3dc8ba9
> 
> finally, please rebase this on `main` as i think it's a bit out of date and a rebase will make testing easier

Morning @taylordowns2000! I considered the first item as out of the scope since it mingles with another app feature, whether the job is executed or not when the trigger is enabled but as there was no exception mentioned before it makes sense to apply  the additional condition to this edge.
For the second item, sorry for the inconvenience, I have relied to much on the automated test case. It works now (labels are preserved during and after edit/save).

For the rebase there was a very recent conflict resolution that brought main changes (8b761f2) but it is also rebased now.

2023-12-14 13:20 UTC, stuartc commented
@jyeshe this is great! I added the two small recommendations in the comments - I also made some some small component/layout changes; I reverted the `font-medium` stuff as well... The app isn't consistent at the moment in this area so I'd rather have it look less than perfect - and change _all_ the components at once than introduce a new variant.

2023-12-14 14:27 UTC, jyeshe commented on lib/lightning/workflows/edge.ex
> +        message: "must be :always or :js_expression when source is a trigger"
Better for user indeed

2023-12-14 14:29 UTC, jyeshe commented
> @jyeshe this is great! I added the two small recommendations in the comments - I also made some some small component/layout changes; I reverted the `font-medium` stuff as well... The app isn't consistent at the moment in this area so I'd rather have it look less than perfect - and change _all_ the components at once than introduce a new variant.

I have customized for the figma style but it makes sense to change for all screens at once.

2023-12-14 15:40 UTC, stuartc commented
> I have customized for the figma style but it makes sense to change for all screens at once.

Awesome thanks, the Figma styles are "idealistic", there's been no endeavour to standardise any of this. 

I mean we do try, but yeah we don't make any effort to either maintain or change if you know what I mean.

So case by case right now.

2023-12-14 15:41 UTC, stuartc commented
@jyeshe I was expecting a validation on the model as well, bonus points for the inputs though, but we should have on the model in case params slip through past the inputs, or they are ever sent via an API etc.

2023-12-14 15:47 UTC, jyeshe commented
> @jyeshe I was expecting a validation on the model as well, bonus points for the inputs though, but we should have on the model in case params slip through past the inputs, or they are ever sent via an API etc.

It was in a separate commit c5cf7b8

2023-12-15 11:37 UTC, stuartc commented
@jyeshe can you rebase and squash/tidy up the commits and I'll merge it 👍

2023-12-15 11:37 UTC, stuartc approved these changes

2023-12-15 11:41 UTC, stuartc commented
@jyeshe I just merged the rename brach, if you could rebase and keep that rename stuff in a single and separate commit if you'd like.

2023-12-15 12:54 UTC, closed without merging