Hide project security setting tab from non-authorized users
OpenFn/Lightning pull request #1566
Opened 2023-12-13 12:24 UTC by midigofrank

## Notes for the reviewer

## Related issue

Fixes #1477

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

2023-12-15 00:33 UTC, elias-ba requested changes
Hey @midigofrank this is looking really great. I just could spot that when you enter the security tab URL in the browser (`http://localhost:4000/projects/4adf2644-ed4e-4f97-a24c-ab35b3cb1efa/settings#security`) it renders this blank page.

![image](https://github.com/OpenFn/Lightning/assets/86059666/132de5b9-7e9b-444a-a052-f264563f7c5b)

2023-12-18 09:51 UTC, jyeshe approved these changes
Even pasting the url it doesn't show the security option :clap: 
Small detail on the testing just to keep the same style with the rest of the code.

2023-12-18 09:51 UTC, jyeshe commented on test/support/conn_case.ex
> +    user = Lightning.Factories.insert(:user)
great you've replaced! importing would look like more with the rest of the code

2023-12-18 09:51 UTC, jyeshe commented on lib/lightning_web/live/project_live/settings.html.heex
> +          :if={can_edit_project(assigns)}
:+1:

2023-12-18 22:56 UTC, elias-ba approved these changes
@midigofrank this is looking great. Nice job 🎉

2023-12-20 15:50 UTC, merged

2023-12-20 15:53 UTC, taylordowns2000 reviewed
@midigofrank , @jyeshe , i've merged this down but want to note two things:
1. there's a commented out console.log that should be removed
2. i don't think this is the quickest fix for the desired UX. we want non admin users to be able to view this interface but for the MFA toggle to be `disabled`. they can _see_ whether it's enabled or not, but not modify it. is that harder to do than hiding the entire page? (hiding the page is _not_ what we want from a UX perspective.)

2023-12-20 16:04 UTC, jyeshe commented
> @midigofrank , @jyeshe , i've merged this down but want to note two things:
> 
> 1. there's a commented out console.log that should be removed
> 2. i don't think this is the quickest fix for the desired UX. we want non admin users to be able to view this interface but for the MFA toggle to be `disabled`. they can _see_ whether it's enabled or not, but not modify it. is that harder to do than hiding the entire page? (hiding the page is _not_ what we want from a UX perspective.) do we have some patterns elsewhere in the app where we make certain buttons or inputs `disabled`?

Hi @taylordowns2000 it was suggested to be hidden on the issue #1477 and I would choose this customization for non-admin as we are preventing to show options to users that they cannot/should not operate.

2023-12-20 16:17 UTC, taylordowns2000 commented
Ah, but we need to actually *SHOW* this stuff to folks who can’t modify it.
No sweat, just a miscommunication. Follow up with Nick in the new years if
you’ve got questions. We’ll open a new issue!

Taylor Downs
CEO, OpenFn <https://www.openfn.org>


On Wed, Dec 20, 2023 at 09:04 Rogerio Pontual ***@***.***>
wrote:

> @midigofrank <https://github.com/midigofrank> , @jyeshe
> <https://github.com/jyeshe> , i've merged this down but want to note two
> things:
>
>    1. there's a commented out console.log that should be removed
>    2. i don't think this is the quickest fix for the desired UX. we want
>    non admin users to be able to view this interface but for the MFA toggle to
>    be disabled. they can *see* whether it's enabled or not, but not
>    modify it. is that harder to do than hiding the entire page? (hiding the
>    page is *not* what we want from a UX perspective.) do we have some
>    patterns elsewhere in the app where we make certain buttons or inputs
>    disabled?
>
> Hi @taylordowns2000 <https://github.com/taylordowns2000> it was suggested
> to be hidden on the issue #1477
> <https://github.com/OpenFn/Lightning/issues/1477> and I would choose this
> customization for non-admin as we are preventing to show options to users
> that they cannot/should not operate.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenFn/Lightning/pull/1566#issuecomment-1864744912>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACCUBLNX7HQVOFGGOBJ3SGTYKMECHAVCNFSM6AAAAABATCJD6WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNRUG42DIOJRGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>