Put adaptor state configuration in a struct to avoid leaking data to sentry
OpenFn/Lightning pull request #1609
Opened 2024-01-11 06:35 UTC by midigofrank

## Notes for the reviewer

- Wraps credential body in a `Lightning.AdaptorState` struct and implements the `Inspect` protocol to hide the data

## Related issue

Fixes #1600 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

2024-01-11 08:58 UTC, taylordowns2000 reviewed
@midigofrank , are there any other places in the application where we use a credential body? (like the attempts service, state assembler, or even credential edit/view?) would they need to use this new struct too?

2024-01-11 15:01 UTC, taylordowns2000 requested changes
per that earlier call, please change `AdaptorState` to `SafeSecrets`

2024-01-12 08:27 UTC, taylordowns2000 approved these changes
looks good. waiting for @stuartc to weigh in here

2024-01-17 12:32 UTC, taylordowns2000 commented on lib/lightning/safe_secrets.ex
> +  end
Great catch @stuartc . I think we actually discussed this already (requested change from `AdaptorState` to `SafeSecrets`) and I missed that it still had the "configuration" bit in my last review.

2024-01-17 12:32 UTC, midigofrank commented on lib/lightning/safe_secrets.ex
> +  end
Hmm, makes sense,  let me update it. And nope, there's no issue with nested data structures

2024-01-18 07:10 UTC, stuartc approved these changes

2024-01-18 07:10 UTC, stuartc approved these changes

2024-01-18 09:10 UTC, merged