Allow users to connect to their GitHub accounts
OpenFn/lightning pull request #1912
Opened 2024-03-19 08:54 UTC by midigofrank

## Validation Steps
### Demo:
https://github.com/OpenFn/lightning/assets/39288959/caa3f05f-49c3-4f1a-9a41-1f4573383def
### Required ENVS:
- `GITHUB_APP_CLIENT_ID`
- `GITHUB_APP_CLIENT_SECRET`
### Checklist

- [x] User can connect
- [x] User can disconnect 

## Notes for the reviewer

- Adds a new column, `github_oauth_token` to the `users` table. This field is encrypted at rest, with the help of `Lightning.Encrypted.Map`
- Adds a new route, `/oauth/:provider/callback` and controller `OauthController`. I've decided NOT to use the existing route and controller `OidcController` because this new logic deals with users who are logged in. Maybe I should merge them in together? 🤷‍♂️ 
- Github supports both non-expiry and expiry tokens. I have handled both cases
- I have defined a global test adapter for `tesla`, `config :tesla, adapter: Lightning.Tesla.Mock`. I think I should have done this in https://github.com/OpenFn/lightning/pull/1781 instead of defining only one for the `GithubClient`. Consequently, I have been forced to `stub` this with the `Hackney adapter` so that the `Bypass` tests work. 

## Related issue

Fixes #1894 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested. 
- [x] If needed, I have updated the **changelog**
- [x] Product has **QA'd** this feature
- [x] The callback urls have been updated in the `prod` and `demo` Github Apps Setting

2024-03-20 08:00 UTC, taylordowns2000 approved these changes

2024-03-20 12:22 UTC, jyeshe reviewed
@midigofrank this is great. Found some opportunities for fail fast, to know directly the root cause of some errors and there is one drift on spec for error handling. Wondering why dialyzer has not caught it :thinking:

2024-03-20 12:22 UTC, jyeshe commented on config/runtime.exs
> +    |> Keyword.get(:client_secret, nil)
If mandatory on prod, would move to prod section and use a `Keyword.fetch!`. Unless we have some instances where the Github feature would be turned off (possibly on a cluster or set of nodes for free users). cc @taylordowns2000

2024-03-20 12:22 UTC, jyeshe commented on lib/lightning/version_control/version_control.ex
> +          {:ok, String.t()} | {:error, :expired | map()}
The spec is a bit different `{:error, :expired}`. Could you double check the error handling?

2024-03-20 12:22 UTC, jyeshe commented on lib/lightning/version_control/version_control.ex
> +  defdelegate subscribe(user), to: Events
:+1:

2024-03-20 12:54 UTC, jyeshe commented on config/runtime.exs
> +    |> Keyword.get(:client_secret, nil)
I have talked with Taylor and the code is correct. The feature might not be used on prod on certain instances.

2024-03-20 13:04 UTC, jyeshe requested changes
Hey @midigofrank I wasn't clear about the timing for this changes (considering the latest planning). I would appreciate if you had a look specially at the error spec and on the fail fast when `client_id` is `nil`. These are important to not affect our MTTR in the future. The other one is a quick/simple style thing. Thank you!

2024-03-22 08:52 UTC, jyeshe approved these changes
This is great! 🌟

PS: The Github disconnect is on a parallel thread on slack (so ignoring the CI error for this PR)

2024-03-22 09:02 UTC, merged