1939 dataclip search index
OpenFn/lightning pull request #1941
Opened 2024-03-26 17:38 UTC by taylordowns2000

## Validation Steps

_How can a reviewer validate your work?_

Fixes #1939

## Review checklist

- [ ] I have performed a **self-review** of my code
- [ ] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

2024-03-29 13:30 UTC, taylordowns2000 commented on lib/lightning_web/live/run_live/index.ex
> +    rejected: :boolean
this is a separate fix — the filters weren't working for "rejected" and this does the trick!

2024-03-29 13:30 UTC, taylordowns2000 commented on lib/lightning_web/live/run_live/index.html.heex
> +                help_text="Use whole words or the start of words for better results; partial string matching often won't find substrings in the middle or at the end of a word."
added to make it easier for users to understand the limitations of this `tsquery`

2024-03-29 13:31 UTC, taylordowns2000 commented on priv/repo/migrations/20240329123743_generate_dataclip_search_vectors.exs
> +      # Calculate the search vectors in batches of 1000 rows until all rows have
this was a great pattern to reuse @stuartc . thank you!

2024-03-29 13:31 UTC, taylordowns2000 commented on priv/repo/migrations/20240329123743_generate_dataclip_search_vectors.exs
> +      SET search_vector = jsonb_to_tsvector('english_nostop', body, '"all"')
the `'"all"'` is magic... it tells postgres to include the keys and the values in the index

2024-03-29 13:32 UTC, taylordowns2000 commented on test/lightning/invocation_test.exs
> +    @tag skip: "Ooops. We don't support this yet."
this is something i'd like to support in the future, but it would be a progressive enhancement from where are now.

2024-04-01 12:06 UTC, jyeshe requested changes
The search worked perfectly for both prefixes and complete words preserving the case insensitive behaviour. 

Only the tooltip was not displayed:
![Screenshot from 2024-04-01 13-03-24](https://github.com/OpenFn/lightning/assets/44991200/87941358-5796-420f-aecb-eeae240d2f4a)

I have opened two issues on the UI related to the search box but not on the scope of indexing.

2024-04-01 12:33 UTC, taylordowns2000 commented
> The search worked perfectly for both prefixes and complete words (keys and values) preserving the case insensitive behaviour.
> 
> Only the tooltip was not displayed: ![Screenshot from 2024-04-01 13-03-24](https://private-user-images.githubusercontent.com/44991200/318425914-87941358-5796-420f-aecb-eeae240d2f4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzQ2MzIsIm5iZiI6MTcxMTk3NDMzMiwicGF0aCI6Ii80NDk5MTIwMC8zMTg0MjU5MTQtODc5NDEzNTgtNTc5Ni00MjBmLWFlY2ItZWVhZTI0MGQyZjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEyMjUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMjVhYzFiNGRkNmU4MjU1NzJmNTFiN2VhYzE1ZjU0NGUwY2I4MWZkOTRiMTQyODI3ZTNiYjA5YzBjYWJiODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jhmtAmS6mkjZFWEsaCBEG7ElbsQCTKHsOdwy26w0AOc)
> 
> I have opened two issues on the UI related to the search box but not on the scope of indexing.

Thank you @jyeshe ! Re: "tooltip not displayed" I can't recreate that problem. Looking closely at the images you've pasted though, it almost seems as though you're running on an old commit. Is that possible? Your screenshot has March 26th and the last commit on this PR was on March 29th

2024-04-01 13:31 UTC, jyeshe approved these changes
@taylordowns2000 Queries were validated and the tool tip is shown :100: With this last revision the search became case insensitive which is coherent with the `ts_query` output shown at:
https://www.postgresql.org/docs/current/functions-textsearch.html

2024-04-01 13:33 UTC, merged