Improve run panel on the inspector
OpenFn/lightning pull request #1945
Opened 2024-03-28 06:30 UTC by elias-ba

## Validation Steps

_How can a reviewer validate your work?_

## Notes for the reviewer

## Related issue

Fixes #1909

## Review checklist

- [ ] I have performed a **self-review** of my code
- [ ] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

2024-03-28 13:04 UTC, taylordowns2000 requested changes
Hey @elias-ba , this may not have been clear in the spec, but the idea was that this panel would take a _maximum_ of 25% (or 33%? i forget) of the vertical space. right now it looks like it's _always_ taking that space. is there a way to make it small unless it actually gets filled up... up to the maximum percentage allocation?

<img width="1592" alt="image" src="https://github.com/OpenFn/lightning/assets/8732845/deb4a9f8-6456-4e81-8414-c6df1800ca59">

Also, looks like the edges at the bottom of the page have broken - the panel content now goes OFF the bottom of the page and the scroll edges no longer look rounded.

<img width="505" alt="image" src="https://github.com/OpenFn/lightning/assets/8732845/edd04ed3-6519-45a9-81c2-e76b509541d1">

2024-03-28 21:46 UTC, elias-ba commented
> Hey @elias-ba , this may not have been clear in the spec, but the idea was that this panel would take a _maximum_ of 25% (or 33%? i forget) of the vertical space. right now it looks like it's _always_ taking that space. is there a way to make it small unless it actually gets filled up... up to the maximum percentage allocation?
> 
> <img alt="image" width="1592" src="https://private-user-images.githubusercontent.com/8732845/317734326-deb4a9f8-6456-4e81-8414-c6df1800ca59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NjI2NTAsIm5iZiI6MTcxMTY2MjM1MCwicGF0aCI6Ii84NzMyODQ1LzMxNzczNDMyNi1kZWI0YTlmOC02NDU2LTRlODEtODQxNC1jNmRmMTgwMGNhNTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMjE0NTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWJlYjhjNGYyYjI1NzI5ZDNjNGM2NWY5ODAwOWJkYTE0NzQwYjdiYjhiYTFiMGI2ZmMyODgzMTcwN2JmNWRkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pyGKLG1pc6wMIMEY6QkHNdwm6GElACCf0ZjPRDdzMyc">
> Also, looks like the edges at the bottom of the page have broken - the panel content now goes OFF the bottom of the page and the scroll edges no longer look rounded.
> 
> <img alt="image" width="505" src="https://private-user-images.githubusercontent.com/8732845/317740280-edd04ed3-6519-45a9-81c2-e76b509541d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NjI2NTAsIm5iZiI6MTcxMTY2MjM1MCwicGF0aCI6Ii84NzMyODQ1LzMxNzc0MDI4MC1lZGQwNGVkMy02NTE5LTQ1YTktODFjMi1lNzZiNTA5NTQxZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMjE0NTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWFkMzcwMmZmODU5NzVhMmQ5OTQyYjE3ZmFmNjc5ODY3ZWIwZTdmNzM5N2YwYWQxODcwMTA3MWU0ZTNkY2UyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eUqWuk-cNeEBaE5Ku2-uarEioHrXA6hkB2g5RIJDVa0">

@taylordowns2000 let me check this out. I might have broken it in the very last changes I made to the CSS. Thanks for catching it

2024-03-31 10:15 UTC, taylordowns2000 approved these changes

2024-04-01 14:52 UTC, taylordowns2000 commented
oooh @jyeshe , do you mean that when a step is clicked from the `Run` tab, the `Logs` panel should be focused?

<img width="870" alt="image" src="https://github.com/OpenFn/lightning/assets/8732845/122f75fd-ac9e-4d73-a6be-4dbe6b675209">

If so, I _think_ @elias-ba and I had decided to move that into the next issue... it was too tricky for this one.

2024-04-01 14:59 UTC, jyeshe approved these changes

2024-04-01 16:00 UTC, merged