Allow multiple projects per repo
OpenFn/lightning pull request #1966
Opened 2024-04-03 14:44 UTC by midigofrank

## Validation Steps

### Required ENVs

- `GITHUB_APP_ID`
- `GITHUB_APP_NAME`
- `GITHUB_APP_CLIENT_ID`
- `GITHUB_APP_CLIENT_SECRET`
- `GITHUB_CERT`
- `REPO_CONNECTION_SIGNING_SECRET`

Check the [README](https://github.com/OpenFn/lightning/pull/1966/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) on how to install `libsodium`

### Acceptance Criteria

#### Connecting 
Users can connect their project to a github repo which they have access to (on github).
Only an `admin` or `owner` can add the github connection. 
<img width="1234" alt="Screenshot 2024-04-04 at 22 07 29" src="https://github.com/OpenFn/lightning/assets/39288959/00152d9a-f8a7-4c14-9996-747c7b1bfcec">

When you click `connect branch`, the following will happen:

- [x] `.github/workflows/openfn-pull.yml` is committed into the **default branch** of the chosen repo
- [x] `.github/workflows/openfn-{{projectId}}-deploy.yml` is committed into the selected branch
- [x] `openfn-{{projectId}}-config.json` is committed into the selected branch
- [x] `ProjectRepoConnection` record is created with an `access_token`
- [x] `OPENFN_{{projectId}}_API_KEY` repo secret is added to the repo whose value is the `access_token` above.
- [x] If you choose _Sync to GitHub immediately upon setup_ , "[skip actions]" is added to the commit message getting in the selected branch and `initiate sync` is called. [skip actions] is included so that the deploy workflow is not triggered.
- [x] If you choose _Deploy from GitHub immediately upon setup_ , "[skip actions]" is NOT added to the commit message getting in the selected branch and `initiate sync` is NOT called. This triggers the deploy workflow in github

#### Reconnecting 
After successful connection, incase your the github repo was not properly setup, you get an option to `reconnect`. 
A properly setup repo meets the following criteria:
- [x] has `.github/workflows/openfn-pull.yml` in the **default branch** 
- [x] has a `.github/workflows/openfn-{{projectId}}-deploy.yml` in the **target branch**
- [x] has a `openfn-{{projectId}}-config.json` in the **target branch**
- [x] has an `OPENFN_{{projectId}}_API_KEY` repo secret

Only an `admin` or `owner` can `reconnect`. 
The reconnect button will only be shown if and only if the acting user has access to the installation, regardless of their role.

#### Disconnecting / Remove Integration
Only an `admin` or `owner` can `disconnect`.

You don't need github oauth setup for your account in order to perform this action. But if you have set it up, the actions below will occur, if you don't they'll just get ignored
- [x] `.github/workflows/openfn-{{projectId}}-deploy.yml` is deleted from the selected branch
- [x] `openfn-{{projectId}}-config.json` is deleted from the selected branch
- [x] `OPENFN_{{projectId}}_API_KEY` repo secret gets removed

Each delete operation will have it's own commit message. We will therefore have **2 commits** 

#### Initialize Sync
This sends a workflow dispatch event to github which in turn triggers the `gh action pull`

Project `editor`, `admin` and `owner`(s) are allowed to initialize sync 

#### API

- [x] Authenticate API requests made using `Bearer repo.connection.access_token`

## Notes for the reviewer

- Dropped the `user_id` column and adds `access_token` to `ProjectRepoConnection`
- Renamed `current_user` assign to `current_resource` on the api route to account `ProjectRepoConnection` as a resource that can used to authorize. Here's the specific change: https://github.com/OpenFn/lightning/pull/1966/commits/c7210f888d8870cacabfc6fc05eec2991534ba4f
- `ProjectRepoConnection` access tokens are prefixed with `prc_`. This prefix is what we use to differentiate it at the authorization plug. Also these tokens are generated the same way we do for `api user token`, i.e. `Joken.sign(%{project_id: "someid"})`
- Deleted the github installation end to end test: https://github.com/OpenFn/lightning/pull/1966/commits/6a80d2b7e503c6d879f1a0bcca1cad5c0401db29 . This because the introduction of oauth tokens makes it a little harder to maintain. For instance, whose account shall we use for the token? What do you think? Am I overcomplicating it?

## Related issue

Fixes #1811
Fixes #1892 
Fixes #1895

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [x] Releases are created for https://github.com/OpenFn/cli-pull-action/pull/1 and https://github.com/OpenFn/cli-deploy-action/pull/1
- [x] Update the `pull` and `deploy` files in the project to point to the openfn actions. They're currently point to `midigofrank/cli-{pull, deploy}-action`
- [x] Product has **QA'd** this feature
- [ ] Generate `PRC_SIGNING_SECRET` for `prod` and `demo`

2024-04-05 10:37 UTC, taylordowns2000 approved these changes

2024-04-08 13:43 UTC, stuartc requested changes
She, this is massive... looks like a fantastic set of work...

I've left a few comments - I haven't looked at everything, but the `prc_` prefix isn't great. I think we should pay the cost of two queries instead of having _all_ tokens need custom parsing to decode.

Also we need to separate out the `default_signer` for joken - the default is just `secret` meaning these can be forged really easily.

I would really like us to use `Lightning.Config` (and Mox) to be the call site for getting the GitHub app config, and allow us to ditch `put_temporary_env` for testing. But I get it if we're running short on time.

2024-04-08 13:43 UTC, stuartc commented on lib/lightning/version_control/project_repo_connection.ex
> +  end
Tell me more about this token, how would we rotate it and where is the signing secret? If it's using the default in `config.exs` we need to enforce using one from an env variable (like we do for the worker)

2024-04-08 13:43 UTC, stuartc commented on lib/lightning_web/components/github_components.ex
> +      href={"https://github.com/login/oauth/authorize?" <> build_query_params()}
can you put this into an assign, I'm not sure that LiveView will optimise this - causing it to be rerendered every time.

2024-04-08 13:43 UTC, stuartc commented on lib/lightning_web/controllers/user_auth.ex
> +         %_{} = resource <- get_current_resource(bearer_token) do
How about? Either way the `%_{}` underscore here doesn't serve any purpose..

```
%{__struct__: type} = resource <- ... do
  if type == User do
    update_last_used(bearer_token)
  end
  
  ...
```

2024-04-08 13:43 UTC, stuartc commented on lib/lightning_web/controllers/user_auth.ex
> +    end
Hmm I'm not in love with the `prc_` prefix on all tokens, right? It's `prc_<JWT>` hey?

2024-04-11 06:30 UTC, stuartc commented on lib/lightning_web/live/profile_live/edit.ex
> +
👌

2024-04-11 08:09 UTC, stuartc approved these changes

2024-04-11 08:19 UTC, merged