Check user limits when adding new users
OpenFn/lightning pull request #1977
Opened 2024-04-08 13:38 UTC by midigofrank

## Validation Steps

- Run test: `mix test test/lightning_web/live/project_live_test.exs:2800`

## Notes for the reviewer

## Related issue

Fixes #1896 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

2024-04-09 12:12 UTC, jyeshe requested changes
Nicely done @midigofrank ! Thank you for the assert and refute descriptions.
I have only two syntactic sugar requests.

2024-04-09 12:12 UTC, jyeshe commented on lib/lightning_web/live/project_live/new_collaborator_component.ex
> +    end
perfect for intermediary checks :+1:

2024-04-11 06:40 UTC, jyeshe approved these changes

2024-04-17 06:23 UTC, stuartc commented on lib/lightning_web/live/project_live/new_collaborator_component.ex
> +  end
Going forward, we should not be putting changesets functions especially when calls to `UsageLimiter` are needed inside LiveViews.

This stuff should be abstracted into `Lightning` and the use of `UsageLimiter` should be hidden inside a module dedicated to handling validation and calling the limiter.

2024-04-17 06:23 UTC, stuartc approved these changes

2024-04-17 06:23 UTC, merged