limit activation of workflows
OpenFn/lightning pull request #1984
Opened 2024-04-15 05:50 UTC by midigofrank

## Notes for the reviewer

- Renames the action to `:activate_workflow` instead of `:new_workflow`
- Checks if the workflow is activated before making call to the limiter.
- `:activate_workflow` is added to the api provisioning flow as well. 
- Introduces a `WorkflowUpdated` event which emitted when the workflow is created/updated. Also when the workflow is marked for deletion  

## Related issue

Fixes #1992 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

2024-04-17 11:25 UTC, stuartc approved these changes
Thanks @midigofrank, I'll merge this - but I think we should move the behaviour inside these helpers into the workflows context. 

I'm not sure what I was thinking putting this in here - but I think these functions have enough responsibility to be part of `Lightning` and not helpers anymore (or at least the limiting part); perhaps not inside `save_workflow` etc but this is business domain logic and should be in Lightning's contexts. 

Lets do something about it in the near future.

2024-04-18 12:47 UTC, jyeshe requested changes
Good job @midigofrank ! The save workflow is working well. Got an error trying to save a job change when the limit has already been reached:
```
[error] GenServer #PID<0.1410.0> terminating
** (Ecto.Query.CastError) deps/ecto/lib/ecto/association.ex:760: value `""` cannot be dumped to type :binary_id in query:

from c0 in Lightning.Credentials.Credential,
  join: p1 in Lightning.Projects.ProjectCredential,
  on: p1.credential_id == c0.id and p1.id == ^"",
  select: c0

    (elixir 1.16.2) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.16.2) lib/enum.ex:1826: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.16.2) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:211: Ecto.Repo.Queryable.execute/4
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ecto 3.10.3) lib/ecto/repo/queryable.ex:151: Ecto.Repo.Queryable.one/3
    (lightning 2.4.0) lib/lightning_web/live/workflow_live/editor_pane.ex:42: LightningWeb.WorkflowLive.EditorPane.update/2
    (phoenix_live_view 0.20.5) lib/phoenix_live_view/utils.ex:498: Phoenix.LiveView.Utils.maybe_call_update!/3
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (phoenix_live_view 0.20.5) lib/phoenix_live_view/diff.ex:681: anonymous fn/4 in Phoenix.LiveView.Diff.render_pending_components/6
```

2024-04-18 12:52 UTC, jyeshe commented
@midigofrank It might be an opportunity to add the limiter to the create workflow button on the dashboard page. It would prevent this error and anticipate to the user that the workflow cannot be created.

2024-04-19 08:03 UTC, jyeshe approved these changes

2024-04-19 09:59 UTC, merged