Persist run options & set at creation (not claim)
OpenFn/lightning pull request #2085
Opened 2024-05-14 14:21 UTC by taylordowns2000

does this feel like the right way to address the run `options` issue?

required context to review:
- https://github.com/OpenFn/lightning/issues/2079
- https://github.com/OpenFn/lightning/issues/2082

2024-05-17 06:15 UTC, taylordowns2000 commented
@stuartc , please take a look here! context in the PR itself

2024-05-23 09:23 UTC, elias-ba commented
@taylordowns2000 this looks like a valid way to implement this. I am not sure I can't validate it's relevancy but it seems to me as a better way of dynamically calculating the run options. Maybe wait for @stuartc to confirm that point.

2024-05-23 09:29 UTC, elias-ba approved these changes
@taylordowns2000 this implementation looks good to me (assuming that tests and other bits will come later)

2024-05-23 10:04 UTC, stuartc reviewed
This looks good, thanks for the detailed PR.

My only comment here is that I think we should make the run options _more_ than a type. Right now it's defined in `RunWithOptions`.

I think is should become an embedded schema, so using Ecto.Schema.

And then in the Run model, it becomes `embeds_one :options, Run.Option`

This will require some light refactoring on `get_run_options` on `UsageLimiter` on both Lightning and Thunderbolt. 

I believe this change will give the run options more prominence and make 'just dumping stuff in' less of a temptation.

2024-05-23 10:05 UTC, stuartc commented
> @taylordowns2000 this implementation looks good to me (assuming that tests and other bits will come later)

Oh and yes, @taylordowns2000 - tests please!

2024-05-29 15:00 UTC, elias-ba requested changes
@taylordowns2000 this is a huge set of great changes. Good job man 🎉. I left a few change requests and questions. Most of the changes are typos and the questions are probably my misunderstanding. 👏🏽

2024-05-30 06:14 UTC, stuartc commented on lib/lightning/extensions/usage_limiter.ex
> +      run_timeout_ms: Lightning.Config.default_max_run_duration() * 1000
Great question, and yes you're correct - the default behaviour is to use the global max run.

2024-05-30 06:16 UTC, stuartc commented on lib/lightning/config.ex
> +  The grace period is configurable and is be used to wait for an additional
:+1:

2024-05-30 07:52 UTC, stuartc requested changes
@taylordowns2000 🙌 this is great!

I made bunch of small changes, namely:

- Using `Lightning.current_time()` for the janitor so we can test against specific times, like in the future etc.
- Changed the Janitor to use a `Repo.stream` approach so we don't try and select all with 1000s of runs (edge case for sure but possible).
- Removed primary key generation for the new embedded schema, we don't need it and Ecto adds one by default.

One biggish thing before we merge is, what happens to existing runs in flight as this is deployed? Is there a fallback, or perhaps we need a migration to default the `options` column?

And while I can totally see that the work orders put options onto new runs for new and retries - I can't see any tests in work_orders_test?

2024-05-30 09:17 UTC, taylordowns2000 commented
nice. think we're good now @stuartc

2024-05-31 06:18 UTC, stuartc approved these changes

2024-05-31 06:20 UTC, merged