Added workflow concurrency queries
OpenFn/lightning pull request #2290
Opened 2024-07-12 10:49 UTC by stuartc

There are two new queries `in_progress_window` and `eligible_for_claim`. Both can be found in the `Lightning.Runs.Query` module.

The effect of these queries in practice is that once a workflow has it's `concurrency` field set, once that number of runs is claimed or started has been reached (even though they arrived first) will not be considered for the next run to be claimed.

The `FifoRunQueue` (the default) queue, now uses the `eligible_for_claim` query to determine which runs to claim next.

## Validation Steps

This PR only adds the queries and uses them on the Fifo queue, so the current expectation for these changes are: on the demo server, or locally - the queue functionality should not result in errors.

## Notes for the reviewer

As mentioned above this does not _yet_ provide the ability to change the limit of a given Workflow, and stands as a potential releasable change that should not cause any regressions.

There is a migration that needs to be run that adds a `concurrency` column to `workflows`.

## Related issue

Re: #2022 

## Review checklist

- [ ] I have performed a **self-review** of my code
- [ ] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

2024-07-12 18:26 UTC, taylordowns2000 commented
This is great @stuartc ! Can I mark this as "ready for review"? (It's currently set to draft.)

2024-07-16 19:24 UTC, christad92 commented
@taylordowns2000 this PR is ready for review. You can rebase your breadcrumbs/navigation branch off this.

2024-07-17 09:40 UTC, taylordowns2000 requested changes
Small UI fixes required:
1. icons stacking vertically rather than horizontally breaks the navbar height
<img width="388" alt="image" src="https://github.com/user-attachments/assets/1fb5e711-5925-4993-b0f0-26579394b5c4">

2. something weird happening with the panel alignment
<img width="857" alt="image" src="https://github.com/user-attachments/assets/0f0b6bfd-2fd0-4ff6-babd-f83faee1d62d">

3. this lock icon (why is it there, what does it do?) becomes a clickable icon-button when i edit the concurrency limit. what happens when i click on it? (i think nothing?)
<img width="371" alt="image" src="https://github.com/user-attachments/assets/e4c9dd98-60ab-4260-ad03-e5e887e712c7">

2024-07-17 11:08 UTC, jyeshe reviewed
This is a wit solution using windows and might be a starting point so that after tackling other bottlenecks the desired concurrency limit chosen by the user can be achieved.

With a single Lightning instance I couldn't get concurrent runs (the tasks were started and finished in different seconds) but with 2 Lightning instances running (4 schedulers online each), it worked like this on the following setups:
Having concurrency limited to 1 all started at happened in different seconds
```
        inserted_at         |         started_at         
----------------------------+----------------------------
 2024-07-17 10:47:40.232147 | 2024-07-17 10:48:07.814647
 2024-07-17 10:47:40.024733 | 2024-07-17 10:48:06.815122
 2024-07-17 10:47:39.789787 | 2024-07-17 10:48:05.800867
 2024-07-17 10:47:39.567228 | 2024-07-17 10:48:04.792769
 2024-07-17 10:47:39.305197 | 2024-07-17 10:48:03.78265
 2024-07-17 10:47:39.054738 | 2024-07-17 10:48:02.772674
 2024-07-17 10:47:38.777204 | 2024-07-17 10:48:01.767813
 2024-07-17 10:47:38.52481  | 2024-07-17 10:48:00.760806
 2024-07-17 10:47:38.28979  | 2024-07-17 10:47:59.749704
 2024-07-17 10:47:38.052512 | 2024-07-17 10:47:58.743348
 2024-07-17 10:47:37.779297 | 2024-07-17 10:47:57.72315
 2024-07-17 10:47:37.533041 | 2024-07-17 10:47:56.71939
 2024-07-17 10:47:37.267834 | 2024-07-17 10:47:55.706062
 2024-07-17 10:47:37.03745  | 2024-07-17 10:47:54.711521
 2024-07-17 10:47:36.792676 | 2024-07-17 10:47:53.691519
 2024-07-17 10:47:36.548745 | 2024-07-17 10:47:52.698209
```
and increasing the concurrency limit to 10 there were 2 per second:
```
2024-07-17 10:43:43.725279 | 2024-07-17 10:43:57.809721
 2024-07-17 10:43:43.474967 | 2024-07-17 10:43:57.236881
 2024-07-17 10:43:43.213388 | 2024-07-17 10:43:56.784074
 2024-07-17 10:43:42.927164 | 2024-07-17 10:43:56.227601
 2024-07-17 10:43:42.663632 | 2024-07-17 10:43:55.759278
 2024-07-17 10:43:42.346453 | 2024-07-17 10:43:55.230034
 2024-07-17 10:43:42.070201 | 2024-07-17 10:43:54.766159
 2024-07-17 10:43:41.723401 | 2024-07-17 10:43:54.208595
 2024-07-17 10:43:40.811433 | 2024-07-17 10:43:53.758506
 2024-07-17 10:43:37.970449 | 2024-07-17 10:43:53.203735
 2024-07-17 10:43:37.757918 | 2024-07-17 10:43:52.742037
 2024-07-17 10:43:37.509206 | 2024-07-17 10:43:52.211224
 2024-07-17 10:43:37.297698 | 2024-07-17 10:43:51.736622
 2024-07-17 10:43:37.042307 | 2024-07-17 10:43:51.202039
 2024-07-17 10:43:36.821591 | 2024-07-17 10:43:50.740235
 2024-07-17 10:43:36.541399 | 2024-07-17 10:43:50.172446
 2024-07-17 10:43:36.307065 | 2024-07-17 10:43:49.745491
 2024-07-17 10:43:36.078432 | 2024-07-17 10:43:49.163867
 2024-07-17 10:43:35.775059 | 2024-07-17 10:43:48.710034
 2024-07-17 10:43:35.52757  | 2024-07-17 10:43:48.161505
```  
(for this test I have increased the worker capacity to 20).

On the UI side as mentioned by @taylordowns2000 there is some room for improvement on the label-field arrangement.

2024-07-17 14:34 UTC, christad92 commented
<img width="358" alt="image" src="https://github.com/user-attachments/assets/9467e2fa-8b39-4547-9ec6-afd59d955354">
@jyeshe

2024-07-17 16:58 UTC, jyeshe approved these changes
For limiting concurrency it works well! Maybe we gonna need to denormalize the runs table if some bottleneck is found but for regular load it's fetching fastly.

2024-07-17 17:13 UTC, taylordowns2000 approved these changes

2024-07-17 18:03 UTC, merged