Allow Revocation Of OAuth Tokens
OpenFn/lightning pull request #2294
Opened 2024-07-12 20:54 UTC by elias-ba

## Validation Steps

## Notes for the reviewer

## Related issue

Fixes #

## Review checklist

- [ ] I have performed a **self-review** of my code
- [ ] I have verified that all appropriate **authorization policies** (`:owner`, `:admin`, `:editor`, `:viewer`) have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Product has **QA'd** this feature

2024-07-13 07:04 UTC, taylordowns2000 commented on lib/lightning_web/live/components/oauth.ex
> +      <.icon name="hero-check-circle" class="h-4 w-4 text-green-600 inline-block" />
@elias-ba 🤣

2024-07-13 07:31 UTC, taylordowns2000 requested changes
This is fantastic @elias-ba . Really great work. I have added the last bit (handling credential delete) and made some language changes. (Notably, we should do our best to _actually follow_ the Oauth2 specification. The field is called `revocation_endpoint`, not `revoke_endpoint` so I've made that adjustment.

Can you implement the tests and re-request review? Thanks!

2024-07-13 09:22 UTC, christad92 reviewed
@elias-ba Amazing work. 

I have spent some time looking at OpenID configurations from different providers and I see that revocation URL is not adopted across board and might be confusing for the users. 

I have seen Microsoft and DHIS2 call it end_session_endpoint whilst some others refer to it as logout_endpoint. 

I'll suggest that we add a subtext to the title that says: "Also known as end_session_endpoint or logout_endpoint

See links below: 
[DHIS/OKTA](https://docs.dhis2.org/en/topics/tutorials/configure-oidc-with-okta.html#:~:text=oidc.provider.okta.end_session_endpoint%20%3D%20https%3A//%7Bclient_domain%7D/oauth2/v1/logout)

[Microsoft](https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration#:~:text=%22end_session_endpoint%22%3A%20%22https%3A//login.microsoftonline.com/common/oauth2/v2.0/logout%22%2C)

There are also platforms like Github and Facebook that do not provide revocation URL but would have us make a DELETE request to a delete token URL. Do we make this field optional and have the fallback of telling the user to manually revoke permission if required?

cc: @taylordowns2000

2024-07-13 09:43 UTC, taylordowns2000 commented
Hey @christad92 , I don't think we support OpenID. Do we?

These endpoints are all part of the required OAuth2 specification. (Not OpenID.)

Sorry if I'm misunderstanding something here.

2024-07-13 10:16 UTC, christad92 commented
My point is some of these applications don't have this endpoint specified as "revocation endpoint" and it's called "end_session_endpoint" or "logout_endpoint".

Thats why I was suggesting that we have a subtext that communicates these options to users when revocation endpoint is not specified in the wellknown file.

2024-07-13 10:57 UTC, taylordowns2000 commented
Hrmmm ok. Let's talk about it on Monday. Phrases like "end session" and "logout" make me think they do something different--is it definitely the same functionality? (We want to revoke a refresh token, not to revoke a session token or "log out" once logged in.)

Also see question above please. Can you find out if we support OpenID? Looks like the DHIS2 link is for OpenID. Is that a different protocol?

Excited to learn about this stuff next week.

2024-07-13 15:03 UTC, elias-ba commented on lib/lightning_web/live/components/oauth.ex
> +      <.icon name="hero-check-circle" class="h-4 w-4 text-green-600 inline-block" />
😆 thanks @taylordowns2000 !

2024-07-17 06:20 UTC, midigofrank approved these changes
Nicely done @elias-ba

2024-07-17 11:32 UTC, christad92 submitted a review, later dismissed

2024-07-17 11:42 UTC, christad92 reviewed
I am still not certain about revocation URL. I have not seen it in any other specs yet.

2024-07-17 17:46 UTC, christad92 approved these changes

2024-07-17 18:58 UTC, taylordowns2000 commented
@elias-ba please rebase (or resolve conflicts). this appears to be all green and good to go once that is done

2024-07-19 17:48 UTC, christad92 reviewed
A few things have changed since the last review: 
- We should not show reauthorize if the user does not provide a revocation URL. We rather tell them to revoke existing access and reauthenticate from the third party app website/portal. 
- The re-authorize URL is set to /credential#
- When a user tries to add a new scope after an initial access, they are unable to remove the scope. So the user is forced to start authorization all over. They should be able to uncheck the box and retain existing auth. 

See video below: 
https://www.loom.com/share/4ddbefaf33364a75a5ab07001e9e3903?sid=68a8c360-4edd-415e-b195-599f3a739dab
<img width="581" alt="image" src="https://github.com/user-attachments/assets/af22524c-5ed3-4cb7-b3ec-39d08f953dc5">

2024-07-19 19:51 UTC, taylordowns2000 commented
Hey @christad92 , shoot me some test data to use for an oauth client please (on slack dm) and I'll wrap this up on Monday!

2024-07-21 09:09 UTC, taylordowns2000 commented on .vscode/settings.json
> +    "editor.defaultFormatter": "animus-coop.vscode-elixir-mix-formatter"
removing this!

2024-07-22 13:44 UTC, closed without merging