2362 remove message sequence protection
OpenFn/lightning pull request #2375
Opened 2024-08-12 16:03 UTC by rorymckinley

### Description

This PR removes any code that was used to specifically manage Kafka messages with keys, ensuring that the message sequence was preserved during processing.

As there is quite a lot going on I grouped the changes in distinct commits, in the hopes that it makes digestion easier.

Closes #2362 

### Validation steps

- Setup a local Kafka cluster based on these [instructions](https://github.com/OpenFn/lightning/blob/main/kafka_testing/KAFKA_ARCHITECTURE.md#testing-locally-using-the-docker-kafka-cluster).
- Ensure that `KAFKA_TRIGGERS_ENABLED` is set to 'yes'
- Set up a Kafka trigger similar t the screenshot below (assuming you have  a topic named `baz_topic`) :

![Screenshot from 2024-08-07 10-07-28](https://github.com/user-attachments/assets/fbd82130-2615-4d73-a98c-521e5b0ee433)

- Publish a message using kcat: `cat message.json | kcat -P -b 127.0.0.1:9094 -t baz_topic`.
- You should see a WorkOrder being enqueued.

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.

2024-08-14 09:04 UTC, jyeshe requested changes
More than happy to review this going back to the original proposed design. It improved a lot the responsiveness and I think we just need to prioritize the rate limiting to protect an overload on the indexation of the workorders dataclips. @christad92 

It looks good for me and I would ask just a rename on an error message to make it consistent with the data format.

2024-08-14 10:47 UTC, rorymckinley commented on lib/lightning/kafka_triggers/message_handling.ex
>          {:error, :data_is_not_json_object}
@jyeshe thanks - I updated it in a new commit.

2024-08-15 08:59 UTC, jyeshe approved these changes
🎉

2024-08-16 15:08 UTC, christad92 approved these changes
Thanks! amazing work!

2024-08-17 07:23 UTC, merged