Hide Export Button When No Work Order
OpenFn/lightning pull request #2501
Opened 2024-09-16 13:22 UTC by elias-ba

### Description

This PR *[adds/changes/fixes]... (A description of your work goes here.)*

Closes #__

### Validation steps

1. *(How can a reviewer validate your work?)*

### Additional notes for the reviewer

1. *(Is there anything else the reviewer should know or look out for?)*

### Pre-submission checklist

- [ ] I have performed a **self-review** of my code.
- [ ] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [ ] I have updated the **changelog**.

2024-09-17 16:04 UTC, midigofrank requested changes
Looks good. Could you update the changelog to match the exact bug?

Is it when no work order exists or when no when no work order is selected?

2024-09-17 16:04 UTC, midigofrank commented on CHANGELOG.md
> +- Hide Export Button When No Work Order
When no work order exists? Or selected? 🤷

2024-09-17 16:16 UTC, elias-ba commented
> Looks good. Could you update the changelog to match the exact bug?
> 
> Is it when no work order exists or when no when no work order is selected?

Nice catch man, thanks a lot. In fact it's when no workorder is matching the filters applied

2024-09-18 06:51 UTC, stuartc approved these changes

2024-09-18 06:51 UTC, merged