2703 getter setter
OpenFn/lightning pull request #2716
Opened 2024-11-27 06:28 UTC by rorymckinley

### Description

This is the first of a series of PRs to cleanup usage of `Snapshot.get_or_create_latest_for`. This functionality was widely used to provide coverage as Lightning migrated to snapshots but is now superfluous for many of the use cases as Workflow creation or modification results in Snapshot creation.

As some of this PR includes updating test fixtures that were relying on the `or_create` functionality, I have used distinct commits to make it more digestible.

#2703 

### Validation steps

This functionality was superfluous so there will be no outwardly visible change. The best validation is probably to confirm that my logic as to the removal of the 'or_create' portion of the functionality is correct.

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

2024-12-09 14:27 UTC, jyeshe requested changes
Super clean and nice introduction of `with_snapshot` on factory. I am being picky again just about the idiom that brings extra work for the compiler.

2024-12-10 11:12 UTC, rorymckinley commented on lib/lightning/workflows/snapshot.ex
> +    multi |> Multi.run(name, get_snapshot)
@jyeshe changed.

2024-12-10 11:13 UTC, rorymckinley commented on lib/lightning/work_orders.ex
> +      changeset |> put_assoc(:snapshot, snapshot)
@jyeshe Changed.

2024-12-10 11:17 UTC, jyeshe approved these changes
Koszy!

2024-12-20 09:53 UTC, midigofrank approved these changes
Nicely done 🙌

2025-01-10 10:26 UTC, merged