Purge Users Data - WIP
OpenFn/Lightning pull request #278
Opened 2022-08-18 02:55 UTC by elias-ba

This PR is a work in progress. I opened because it ships a huge feature and I need pre-reviews on it.

What's done:
- [x] User marks himself for deletion
- [x] Oban performing permanent deletion

What's left:
- [] Super user deletes users
- [] logout user after deletion and prevent future logins

Will close #195

2022-08-22 10:01 UTC, taylordowns2000 requested changes
@elias-ba , looking good. please address each comment

2022-08-22 10:07 UTC, elias-ba commented on lib/lightning/accounts.ex
> +    from(u in User, where: is_nil(u.scheduled_deletion)) |> Repo.all()
@taylordowns2000 we don't wanna display scheduled for deletion users in the users index page.

2022-08-22 10:11 UTC, elias-ba commented on test/lightning/accounts_test.exs
> +  test "list_users/0 returns all users not scheduled for deletion" do
@taylordowns2000 if we introduce the notion of scheduling for deletion, then we either:
- don't wanna display users scheduled for deletion
- or have a column in that page that flags users scheduled for deletion

I decided that it's better to hide users scheduled for deletion.

cc: @amberrignell

2022-08-22 10:12 UTC, elias-ba commented on test/lightning/accounts_test.exs
> +  test "schedule user for deletion" do
@taylordowns2000 We no longer have a `delete_user/1` functionality. We have schedule for deletion.

2022-08-22 10:35 UTC, elias-ba commented on test/lightning_web/controllers/user_session_controller_test.exs
> +    test "a scheduled for deletion user can't log in", %{
done

2022-08-22 10:36 UTC, elias-ba commented on test/lightning/accounts_test.exs
> +    test "Oban removes all users past deletion date" do
Done

2022-08-22 10:43 UTC, elias-ba commented on config/runtime.exs
> +       {"* * * * *", Lightning.Accounts, args: %{"type" => "purge_deleted"}}
Done

2022-08-22 11:25 UTC, taylordowns2000 commented on lib/lightning/accounts.ex
> +    from(u in User, where: is_nil(u.scheduled_deletion)) |> Repo.all()
@elias-ba , please restore this function to how it was before. your test will be failing, and we'll make it pass via a new column in that superuser users list view.

2022-08-22 11:51 UTC, elias-ba commented on test/lightning/accounts_test.exs
> +  test "schedule user for deletion" do
Action here: restore `delete_user/1` and it's corresponding tests

2022-08-23 02:31 UTC, elias-ba commented on lib/lightning/accounts.ex
> +    from(u in User, where: is_nil(u.scheduled_deletion)) |> Repo.all()
Done

2022-08-23 02:37 UTC, elias-ba commented on test/lightning/accounts_test.exs
> +  test "schedule user for deletion" do
Done

2022-08-23 02:37 UTC, elias-ba commented on test/lightning_web/live/profile_live_test.exs
> +      {:error,
Done

2022-08-23 02:46 UTC, elias-ba commented
> @elias-ba , looking good. please address each comment

@taylordowns2000 this is now good and ready for another round of review. You'll probably need to handle the different #TODOs, they're blocking Circle CI.

2022-08-23 02:56 UTC, elias-ba commented
@taylordowns2000 I have rebased against main to handle conflicts but I didn't squash commits. There are a lof of them and I really think most of them are good chunks of work. Maybe you'll take time to squash some of them but to my mind this is really not necessary.

2022-08-25 11:06 UTC, taylordowns2000 commented
@amberrignell , this is ready for your review. if you're happy with how it behaves (and i think you've already checked most of it out) then i'll squash and merge. note that there are some code style issues that i've moved into https://github.com/OpenFn/Lightning/issues/290 but we can address them as a team after this is in main if these tests give you what you need to ship the deliverable

2022-08-26 06:25 UTC, merged