Git-ignore files from mix assets.deploy
OpenFn/lightning pull request #2789
Opened 2024-12-17 10:11 UTC by jyeshe

### Description

This PR fixes the git ignore on Lightning for files generated by mix assets.deploy

Closes #2788 

### Validation steps

1. Run mix assets.deploy (before and after)

## AI Usage

Please disclose how you've used AI in this work (it's cool, we just want to know!):

- [ ] Code generation (copilot but not intellisense)
- [ ] Learning or fact checking
- [ ] Strategy / design
- [ ] Optimisation / refactoring
- [ ] Translation / spellchecking / doc gen
- [ ] Other
- [x] I have not used AI

You can read more details in our [Responsible AI Policy](https://www.openfn.org/ai#pull-request-templates)

### Pre-submission checklist

- [x] I have performed a **self-review** of my code.
- [x] I have implemented and tested all related **authorization policies**. (e.g., `:owner`, `:admin`, `:editor`, `:viewer`)
- [x] I have updated the **changelog**.
- [x] I have ticked a box in "AI usage" in this PR

2024-12-17 11:12 UTC, taylordowns2000 reviewed
I suppose this is fine, but why have I never had any issues with these files before? Is `mix assets.deploy` actually used in any part of developing Lightning?

2024-12-17 12:19 UTC, jyeshe commented
> I suppose this is fine, but why have I never had any issues with these files before? Is `mix assets.deploy` actually used in any part of developing Lightning?

This is not an issue per se but there were recurring requests that these files should be gitignored on the billing app. When the assets are deployed on the umbrella app it invokes all apps.

The `mix assets.deploy` is needed on releases and when it's done via Dockerfile we don't see them locally. 

At last, the billing app can probably work now without digested deployment but this PR helps to avoid showing those files again (a following will be provided for the billing app).

2024-12-18 03:29 UTC, midigofrank requested changes
Hey @jyeshe, great job!.

I'm worried about these two though:
```
/priv/static/images/*-*.png
/priv/static/images/*-*.svg 
```

We already have some images in there that were manually placed in there. Also, if we ever want to add a new image, where would we put it?

2024-12-18 08:25 UTC, jyeshe commented
> Hey @jyeshe, great job!.
> 
> I'm worried about these two though:
> 
> ```
> /priv/static/images/*-*.png
> /priv/static/images/*-*.svg 
> ```
> 
> We already have some images in there that were manually placed in there. Also, if we ever want to add a new image, where would we put it?

Thanks Frank, that's correct. New ones are always ignored locally in favour of saved ones and one needs to intentionally replace them with `git add -f`

2025-01-07 06:38 UTC, midigofrank approved these changes

2025-01-07 08:55 UTC, merged