196 new credential from builder modal
OpenFn/Lightning pull request #351
Opened 2022-09-28 06:10 UTC by wanecode

## Any notes for the reviewer ?

## Related issue

Fixes #196 Create a new credential from within the workflow builder

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If needed, I've updated the changelog
- [ ] Amber has QA'd this feature

2022-09-30 07:04 UTC, wanecode commented
Hey @amberrignell , could you please check this feature.
- create a new credential from an existing job in the builder
- create a new credential from a new job in the builder
- create a new credential from the job form (new job button or edit a job from the job table)

2022-10-06 10:40 UTC, taylordowns2000 requested changes
@wanecode , please make sure that _YOU_ check your PR before requesting a review. `generated_project.yaml` does not belong in here. I think we solved this problem on `main`, you may have added a file to your commit by accident.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/8732845/194292625-5cf633a7-0609-42de-8a62-74f4ea5cd62b.png">

2022-10-07 07:39 UTC, wanecode commented
> @wanecode , please make sure that _YOU_ check your PR before requesting a review. `generated_project.yaml` does not belong in here. I think we solved this problem on `main`, you may have added a file to your commit by accident.
> 
> <img alt="image" width="379" src="https://user-images.githubusercontent.com/8732845/194292625-5cf633a7-0609-42de-8a62-74f4ea5cd62b.png">

2022-10-07 07:42 UTC, wanecode commented
> > @wanecode , please make sure that _YOU_ check your PR before requesting a review. `generated_project.yaml` does not belong in here. I think we solved this problem on `main`, you may have added a file to your commit by accident.
> > <img alt="image" width="379" src="https://user-images.githubusercontent.com/8732845/194292625-5cf633a7-0609-42de-8a62-74f4ea5cd62b.png">

Yes. It was an accident. Sorry

2022-10-10 12:03 UTC, stuartc requested changes
@wanecode good job overall dude! I've made a few comments that could improve things (mostly around decoupling the form from other modules).

2022-10-10 12:03 UTC, stuartc commented on lib/lightning_web/live/job_live/inspector_form_component.ex
> +                Phoenix.LiveView.JS.push("new-credential", value: @job_params)
I believe `phx-click="new-credential"` and `phx-value={@job_params}` should have the same effect.

I don' think we need the JS.

2022-10-12 12:11 UTC, merged