Docs panel
OpenFn/Lightning pull request #435
Opened 2022-11-16 19:24 UTC by josephjclark

This PR replaces the existing compiler/adaptor docs component with a new documentation panel.

This PR is basically just glue code - the heavy implementation logic is off in the `adaptor-docs` package in `kit`. Most improvements will take place over there.

* [x] Render docs below the editor
* [ ] Render the docs vertically (and force the panel to be a little wider)
* [x] Insert text snippets into Monaco

Before this can be tested, we need to publish new `adaptor-docs` and `describe-package` versions over in `kit`.

## Notes on Text insertion

So I've got text insertion working but its a pretty barebones solution. And it's the kind thing that when you plug it in, you realise the UX is just the worst and you wonder if it's worth it.

The idea right now is a rough and ready solution, so that's what we've got.

It uses DOM events now to talk between the Editor and Docs components. This breaks all the patterns in both React and Live View, so it's not something I expect to live for very long :sweat_smile: 

Ultimately this needs to be a single React hierarchy which both components live inside - that will give us a much slicker integration. In my opinion though that's a job for another day.

UX problems include:
* When you click Copy, there's no feedback that anything has happened (we'll fix that over in `kit`)
* When you insert, it may not be obvious where your cursor is
* After you insert you probably want some kind of autoformatting right away
* Given the nature of our Operations I suspect we always want to insert onto a new line?
* If there is no selection it'll default to 0,0, but actually by default we probably want to post a snippet at the end. But how do we know if 0,0 is where the user really wants to be or if it's just the default focus?
* After inserting we may need to scroll to the insert position (especially we've inserted at the end)

It may end up being better if we a) just use Copy, b) take over Monaco's code complete and allow snippets to be inserted through the editor's own UI (at least you're firmly in context there, and if we can work out how to utilise it there's a pretty good UI framework we can build into).

2022-11-17 12:38 UTC, josephjclark commented on assets/package.json
> +    "@openfn/adaptor-docs": "file:../../kit/dist/openfn-adaptor-docs-0.0.1.tgz",
Obviously these dependencies are wrong but I can't update them properly until the actual packages are released. For now, use the export utility in `kit` to test locally.

2022-11-17 12:39 UTC, josephjclark commented
Ok @stuartc this one is also good to go!

2022-11-17 13:52 UTC, stuartc requested changes
Dang, we have CSS issues with our approach. We might have them with the older component too?

What happens is that the component injects it's styles programmatically; which just messes with the existing tailwind config.

![image](https://user-images.githubusercontent.com/144796/202463311-6135d432-01e5-4b40-bfdd-9bd05f895273.png)
![image](https://user-images.githubusercontent.com/144796/202463646-c23d9d87-b7e7-4f72-a1be-269fd1ebf835.png)

I don't think we can merge this until we have a strategy for the CSS. I'm not super clued up on the different approaches available for this kind of problem.

2022-11-17 14:19 UTC, stuartc commented
I think we’re going to have to produce a separate css file for these components to allow the consumer to decide when to import it.

And we should investigate tailwinds purge functionality to avoid duplication of styles.

2022-11-17 14:24 UTC, josephjclark commented
Oooh so that explains why my CSS was screwy. Dang.

Let me look into this.

My immediate reaction is that producing a seperate CSS for the components won't really help because when we import that into the page, it'll still duplicate styles and interfere with tailwind.

I do wonder why this is causing issue and `workflow-diagram` isn't....

2022-11-18 07:21 UTC, merged

2022-11-18 07:22 UTC, stuartc commented
@josephjclark https://github.com/OpenFn/kit/pull/85#issuecomment-1319637048 - managed to merge this in with the changes I made in https://github.com/OpenFn/kit/pull/87