Delete job from inspector
OpenFn/Lightning pull request #455
Opened 2022-11-25 08:42 UTC by elias-ba

## Any notes for the reviewer ?

## Related issue

Fixes #416 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] If needed, I've updated the changelog
- [ ] Amber has QA'd this feature

2022-11-25 12:15 UTC, amberrignell commented
Hey @elias-ba this looks good. If the user is deleting a job with downstream jobs, could you show them the "Unable to delete this job" error immediately (rather than showing the 'This action is irreversable ..." message first (this gives them the impression that it is possible, which is a it misleading).

2022-11-28 11:55 UTC, amberrignell commented
Looks good to me - thanks Elias

2022-11-29 05:58 UTC, stuartc requested changes
@elias-ba This is great! A few small changes but otherwise this is good to go.

2022-11-29 05:58 UTC, stuartc commented on lib/lightning/jobs.ex
> +    |> Repo.delete()
Lovely :+1:

2022-11-29 05:58 UTC, stuartc commented on lib/lightning_web/live/job_live/job_builder.ex
> +
I have a concern here about performance, see: https://hexdocs.pm/phoenix_live_view/assigns-eex.html#change-tracking

I think that a `@is_deletable` assign should be added to `update/3`, without that we run the risk of the database being called with every render (i.e. `handle_event/3`).

2022-11-29 05:58 UTC, stuartc commented on lib/lightning_web/live/job_live/job_builder.ex
> +              title={delete_job_title(@job_id)}
Instead of calling a function here, use an expression like `if @is_deleteable, do: "x", else: "y"`

2022-11-29 05:58 UTC, stuartc commented on test/lightning/jobs_test.exs
> +               [constraint: :foreign, constraint_name: "jobs_trigger_id_fkey"]}} in changeset.errors
By the way there is a helper for these kinds of matches.

Example from `AccountsTest`:

```
assert %{
  password: ["can't be blank"],
  email: ["can't be blank"]
} = errors_on(changeset)
```

2022-11-29 05:58 UTC, stuartc commented on test/lightning_web/live/job_live_test.exs
> +          workflow_id: job.workflow_id
What about the functions from `JobFixtures`? Can you try replace the call to `create_job` with `workflow_job_fixture` from the fixtures?

2022-12-01 13:40 UTC, stuartc approved these changes

2022-12-01 13:40 UTC, merged