Project digest
OpenFn/Lightning pull request #619
Opened 2023-01-31 08:32 UTC by elias-ba

## Any notes for the reviewer ?

## Related issue

Fixes #585 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If needed, I've updated the changelog
- [ ] Amber has QA'd this feature

2023-02-16 11:32 UTC, amberrignell requested changes

2023-02-16 11:32 UTC, amberrignell commented on lib/lightning/accounts/user_notifier.ex
> +    body = Enum.map_join(data, fn d -> build_email_body(d, digest) end)
Could you add an introductory line
"Hi ${user.name}, 

Here's the digest for your project ${project name}."

2023-02-21 23:01 UTC, elias-ba commented
Closing in favor of #648

2023-02-21 23:01 UTC, elias-ba commented
Closing in favor of https://github.com/OpenFn/Lightning/pull/648

2023-02-21 23:01 UTC, closed without merging