Fix broken links in failure alert email
OpenFn/Lightning pull request #735
Opened 2023-03-27 14:44 UTC by elias-ba

## Notes for the reviewer

## Related issue

Fixes #732 

## Checklist before requesting a review

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [x] Amber has **QA'd** this feature

2023-03-27 20:37 UTC, taylordowns2000 approved these changes

2023-03-28 05:57 UTC, amberrignell approved these changes

2023-03-28 06:02 UTC, stuartc requested changes
All good here @elias-ba, but you forgot to update the CHANGELOG.

Please rebase to get the CI fix and update the changelog

2023-03-28 11:24 UTC, stuartc approved these changes

2023-03-28 11:25 UTC, merged