Users can only delete their own account
OpenFn/Lightning pull request #820
Opened 2023-05-03 11:59 UTC by elias-ba

## Notes for the reviewer

## Related issue

Fixes #

## Checklist before requesting a review

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Amber has **QA'd** this feature

2023-05-05 11:24 UTC, amberrignell requested changes

2023-05-05 13:26 UTC, stuartc commented
@elias-ba this is great, let me know when you have made the changes you wanted/needed to do:

- Moving the docs around
- Refactoring the repetitiveness of the tests to use a helper of some kind (optional, your choice).

2023-05-08 14:34 UTC, elias-ba commented on README.md
> +end
Done

2023-05-10 07:59 UTC, amberrignell approved these changes

2023-05-10 08:26 UTC, stuartc approved these changes

2023-05-10 08:26 UTC, merged