wip: pseudo code for refresh_token
OpenFn/Lightning pull request #854
Opened 2023-06-01 15:19 UTC by mtuchi

## Steps

- Write a function that can tell the difference between a token that is about to expire and one that is not
- Write a test for Google.refresh_token()
- Write Credentials.refresh_token()
- Put the refresh_token() function in the Runner

## Related issue

Fixes #

## Review checklist

- [ ] I have performed a **self-review** of my code
- [ ] I have verified that all appropriate **authorization policies** have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Amber has **QA'd** this feature

2023-06-16 08:54 UTC, amberrignell commented
Closing this PR for now as it won't be worked on for a while. Left a comment on the issue so that whoever picks it up can keep going on the same branch with the existing work that has already been done

2023-06-16 10:03 UTC, taylordowns2000 commented
sounds good. coincidentally, @mtuchi and i were just discussing this as it relates to the new `msgraph` adaptor (which relies on oauth)

2023-06-28 14:20 UTC, taylordowns2000 requested changes
td note to self

2023-06-29 12:09 UTC, taylordowns2000 approved these changes

2023-06-30 07:50 UTC, merged