SQL script for converting triggers to edges
OpenFn/Lightning pull request #889
Opened 2023-06-20 07:36 UTC by elias-ba

## Implementation plan

- [ ] for each trigger where type = `cron`, create an edge from that trigger to its associated job with condition `'always'`
- [ ] for each trigger where type = `on_job_success`, create an edge from the upstream job to the downstream job with condition `'on_job_success'`
- [ ] for each trigger where type = `on_job_failure`, create an edge from the upstream job to the downstream job with condition `'on_job_failure'`

## Notes for the reviewer

## Related issue

Fixes #875 

## Review checklist

- [ ] I have performed a **self-review** of my code
- [ ] I have verified that all appropriate **authorization policies** have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Amber has **QA'd** this feature

2023-06-23 11:41 UTC, zacck requested changes

2023-06-23 11:41 UTC, zacck commented on lib/lightning_web/live/credential_live/edit.ex
Hey @elias-ba  why this change?

2023-06-23 11:50 UTC, elias-ba commented on lib/lightning_web/live/credential_live/edit.ex
I am suprised by this being in this branch. But it's still a change we need in the app. That code is no longer needed.

2023-06-27 11:03 UTC, taylordowns2000 approved these changes

2023-06-27 11:03 UTC, merged