Bulk rerun workorders from a specific job
OpenFn/Lightning pull request #906
Opened 2023-06-26 16:18 UTC by midigofrank

## Notes for the reviewer

## Implementation Plan
### UI 
- [x] Display rerun from... button when the selected workorders are only for a single workflow
- [x] Add confirmation modal
- [x] Order the steps accordingly in the modal
- [x] Add relevant tests
### LOGIC
- [x] Add function to filter attempt runs based on given job_id

## Related issue

Fixes #833 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [ ] If needed, I have updated the **changelog**
- [ ] Amber has **QA'd** this feature

2023-06-30 07:25 UTC, taylordowns2000 commented
hey @midigofrank , it's not quite possible to do an ordered list (as there are multiple _branches_ in workflows. please go alphabetical for now).

2023-07-01 10:27 UTC, taylordowns2000 requested changes
Looking good. A few things:

1. Possible regression on #659  - When I select three workorders from 2 different workflows, the modal tells me that i've only selected two of workorders. I'm pretty sure this bug is introduced by the use of `selected_workflow_count(...)` which is now being used for to set the value of `selected_count`. You still need that `@selected_count` attribute to be the count of how many work orders have been selected. (Don't change it!) To deliver this new feature, you've also got to introduce something along the lines of `@distinct_workflows_in_selection` which will count the number of different workflows.

<img width="921" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/0dc004fa-be83-4b18-b658-0ec46dd7ea77">

2. You've gone off-spec with the "Oops, chosen step hasn't been run in the latest attempt of any of the selected workorders" concept and I really like the concept behind it, but if you're adding to the UX we need to make it really work. there are three big issues with how it's implemented now, which would not be problematic if the modal succesfull sent the workorder to the backend, closed, and notified the user that `0 workorders have succesfully been enqueued.`. The problems are: (a) the modal stays open after that message is displayed but you don't let me pick another step and try again. instead the user must dismiss the notification, close the modal, and then re-open the modal to get the button to work again. (b) after closing the modal, the screen focus is lost and you must click TWICE to get anything to work again on that page. did a process die? (c) dismissing the notification also dismisses the modal. 

i like where you're heading with this, but please address those new UX problems!

3. the re-run from doesn't appear to work. in the image below, i've selected a workorder that failed on the "transform data to FHIR standard" step and opted to re-run it from that step. no new attempt is made and i get the warning message from point 2.
<img width="1055" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/7c5629aa-ef84-42db-863d-106298264a44">

in this next image, i'd expect 1 of the 3 selected workorders to result in a new attempt since the final attempt of that third workorder has the step i've chosen.

<img width="1033" alt="image" src="https://github.com/OpenFn/Lightning/assets/8732845/f550cd8b-0999-44a9-9aff-9481ec50ead4">

ping me on slack if you want to chat through any of this.

2023-07-03 06:16 UTC, taylordowns2000 commented
Ok. I’ve sent you a note over there. Meet at 930 EAT?

On Mon, Jul 3, 2023 at 06:15 Midigo Frank ***@***.***> wrote:

> Good catch @taylordowns2000 <https://github.com/taylordowns2000> . I have
> been able to fix the UI issues. However, I'm not sure why the
> list_for_rerun_from_job query lists AttemptRuns for jobs that aren't part
> of the given Attempt. Looks like I'm missing something, plus it also
> means that the test I wrote for that function is incorrect. Let's go over
> it in slack.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenFn/Lightning/pull/906#issuecomment-1617358444>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACCUBLPXKS75PUCWBK7WT4LXOJIOTANCNFSM6AAAAAAZUMT3ME>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-03 10:34 UTC, amberrignell requested changes
Hey @midigofrank - looking good but there's a small of bug: 

When I select rerun from... for one workflow then another, sometimes the job options do not get updated. To reproduce, create a workflow 1 and a workflow 2 with several runs each, then click "rerun from" for one after the other. You will see that sometimes the job options show to rerun workflow 1 are the jobs from workflow 2.
(I think this is related to liveview not updating)

Please also fix the second modal following [Taylor's fix](https://github.com/OpenFn/Lightning/commit/9b74275e29319a7f75aa9dd640fa93fbf8362093) for the first

2023-07-03 13:07 UTC, amberrignell commented
Oh and sometimes it seems I need to click the "rerun from.." button twice for it to work? Do you have a fix for that?

2023-07-03 17:29 UTC, taylordowns2000 commented
hey @midigofrank , i found and fixed the issue that @amberrignell identified, but I still want your eyes and opinions here: https://github.com/OpenFn/Lightning/pull/906/commits/e67773d288233d04c87a65efd2de46b91e8c64b6

I think the issue is a double-whammy:

1. the root cause is that this `selected_work_orders` assign is not a list of work orders. It's way more complicated than that. It's a Map, with 0..N keys. Each key has a list value with [0..N] items. The items inside those lists are workorders. Does it need to be this complicated? Could we not have one assign for `selected_workorders` and another for `selected_workflows`? Is there something driving this complexity?
2. Assuming that yes, we need that list of workorders to be grouped into a map and keyed by workflow_id, then the issue is in how you use that `Map.update`. I don't know much about Map.update, so I've proposed a fairly hacky solution... but it's not enough to remove the value from the list of workorders under each key. If there are no workorders left under that key, you also need to remove the _key itself_. Otherwise if you select a workorder from WF1, then unselect it and select a workorder from WF2, your `workflow_id={@selected_work_orders |> Map.keys() |> hd()}` code (which also seems a little icky to me) won't work properly. It will randomly the `hd()` and show the user a list of jobs for a workflow that has no selected items.

Regardless of whether or not you want to change the naming/design to reduce the complexity, would you please add a test that locks in this new behavior and shows that the old "select-then-unselect-workorders-from-different-workflows" bug is gone?

2023-07-04 18:16 UTC, taylordowns2000 requested changes
hey @midigofrank  looks great!

@amberrignell pointed out that the order of these retries getting sent to the processor is reversed. i don’ know if this was on the spec or not (apologies if not) but i’ve pushed an extension to your tests which now fails: https://github.com/OpenFn/Lightning/pull/906/commits/02348b83175a8af88c7a407f92b8a40b69d52fd1

i’ve also included in the commit a sample fix, though I don’t think it’s working the way we want it to.

can you try to ensure that the order we send these retries is: retry the oldest associated work_order FIRST and the newest associated work_order LAST?

feel free to overwrite all of my code in that commit to guarantee that the order we send these for reprocessing is `[asc: work_order.inserted_at]`

2023-07-06 11:25 UTC, merged