Workflow Diagram: Fixes and refactors
OpenFn/Lightning pull request #936
Opened 2023-07-11 16:55 UTC by josephjclark

This PR introduces a bunch of fixes, refactors and improvements to the workflow diagram. The cosmetic stuff will be based on top of this.

Coming back into this after a while was pretty  difficult. Complexity and various changes since I last looked haven't helped (I don't know why the store is down in the component now, but I don't intend to move it back)

* [x] Remove Context - we just don't need it (yet)
* [ ] Simplify the `workflow`, `_workflow` and `model` stuff
* [x] Move some code out of Workflow Diagram (it's massive, there's way too much stuff in it)
* [x] Fix (placeholder) node removal  - this looked to be totally broken
* [x] Don't run layout on every single update
* [ ] Fix edge selection

2023-07-12 17:46 UTC, josephjclark commented on assets/js/workflow-diagram/WorkflowDiagram.tsx
> -          if (chartCache.current.deferSelection) {
Very happy to see the back of all this!!

2023-07-12 18:30 UTC, taylordowns2000 requested changes
@josephjclark , this seems almost perfect, but i'm still noticing that when i:
1. refresh my page
2. select an edge
3. change the edge condition
4. then hit `ctrl-s`
the save doesn't work. if i touch other parts of the diagram (trigger or job) it seems to work. are you getting that same issue?

2023-07-12 18:39 UTC, josephjclark commented
> @josephjclark , this seems almost perfect, but i'm still noticing that when i:
> 
> 1. refresh my page
> 2. select an edge
> 3. change the edge condition
> 4. then hit `ctrl-s`
>    the save doesn't work. if i touch other parts of the diagram (trigger or job) it seems to work. are you getting that same issue?

I have not noticed this - I'll take a look!

I've also just remembered  that I need to ensure that selection is remembered properly on load and refresh - I'll get that sorted in the morning.

2023-07-13 10:31 UTC, josephjclark commented
@taylordowns2000 I am noticing a bunch of issues around save and I don't think they're directly related to changes on this branch.

Most edits seem to be OK, occasionally I don't get the flash message. I think that if the editor widget is closed/hidden, the save fails.

On `nodes-and-edges-release` If the editor is closed, the save fails every time. I can't really check that on edges on that branch because edge selection is so flaky!

2023-07-13 10:34 UTC, josephjclark commented
I would like @stuartc to review this but as he's going to be dark for a few days and the changes are important, I'm gonna suggest we merge as soon as it passes QA.

2023-07-13 13:01 UTC, stuartc commented
@josephjclark if you think it's ready, I would be happy to merge it... I'm doing 'delete a node' right now and the layout/render logic may or may not need tweaking so best I be on the latest and greatest.

2023-07-13 13:14 UTC, merged