feat: admins can require MFA for their project users
OpenFn/Lightning pull request #993
Opened 2023-07-27 19:02 UTC by midigofrank

## Notes for the reviewer

- [x] Add `requires_mfa` field to `projects` table
- [x] Add security tab to project settings page
- [x] Use `can_edit_project` permission to determine who can toggle MFA
- [x] add relevant tests

## Related issue

Fixes #892 
Fixes #893 

## Review checklist

- [x] I have performed a **self-review** of my code
- [x] I have verified that all appropriate **authorization policies** have been implemented and tested
- [x] If needed, I have updated the **changelog**
- [x] Product has **QA'd** this feature

2023-07-27 21:34 UTC, taylordowns2000 requested changes
thanks @midigofrank .
1. please add a test showing that editors and viewers cannot flip the toggle
2. please either continue work on this branch (and we'll wait to merge until the requirement in enforced) or remove the line from the changelog.

re: 2, either one is fine, but we can't say "Project owners can require MFA for their users" in the change-log until that's actually true! my vote would be to continue your work here, let's hold off on the merge until the enforcement is done.

2023-07-28 13:40 UTC, taylordowns2000 commented
@midigofrank , i'm marking this as draft until it's ready with the enforcement

2023-07-28 16:27 UTC, taylordowns2000 commented
Admin please.

On Fri, Jul 28, 2023 at 17:23 Midigo Frank ***@***.***> wrote:

> Hey @taylordowns2000 <https://github.com/taylordowns2000> and
> @amberrignell <https://github.com/amberrignell> , is it only the project
> owner who should enable MFA? Or should an admin be able to as well
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenFn/Lightning/pull/993#issuecomment-1655964294>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACCUBLIADRJRL2DLTCBKTDTXSPRQ5ANCNFSM6AAAAAA22QGHIU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-01 11:32 UTC, taylordowns2000 approved these changes
@stuartc , i've approved this PR from @midigofrank - it looks great!

please note that I've also _added_ a new bit... the `:user_scope`.

I'm not sure if this is the best way to do it, but I noticed your use of a `:project_scope` hook that could pull in available projects when mounting certain live views. I hope i've done it right. basically, even when outside the project scope, we now need a list of available projects so that the user can access project X, even if project Y requires MFA.

with your approval this is good to merge.

2023-08-02 12:44 UTC, stuartc commented
@taylordowns2000 I'm not entirely sure about the change you made with the projects list, if I go to my users profile (which does have access to a project), I see:

![image](https://github.com/OpenFn/Lightning/assets/144796/d416a267-3cae-4922-8009-a41927ab2918)

So it looks like the `projects` assign isn't being passed down to the menu component...

However!

I don't think there should be a project list in the user areas... since almost everything is different... for example the menu items are different as well..

I think we should provide a way to "leave" the user area, like we have with super users - provide visual ques and/or colour changes to show that the user isn't in the root of the application...

2023-08-02 14:28 UTC, stuartc requested changes
Hey @midigofrank, lovely work, thank you!

I don't think this was really announced anywhere you would have seen, but we're trying to move off of our fixtures modules - and use ExMachina.

So while that would be _lot_ of work just changing everything - we do want to try and get and new tests written without the use of the fixtures. I changed one or two of them on your changes for an example - there should be a lot more around the project.

I'd like to ask you change at least the new tets you have introduced to use the Factories instead.

And please move the MFA user fixture into the factories module.

Other than that, great work!

2023-08-02 14:28 UTC, stuartc commented on test/lightning_web/live/workflow_live/index_test.exs
> +      user = user_with_mfa_fixture()
Could you move the new `user_with_mfa_fixture` into the Factories module and rewrite it to conform with ExMachinas' API.

2023-08-02 14:28 UTC, stuartc commented on test/lightning_web/live/workflow_live/index_test.exs
> +        )
I've changed one or two of the previous calls to `Projects.create_project(...)`, as with the request about the mfa fixture, please when writing new code could you try and not use things for the fixtures module and rather use/extend the `Factories` module.

2023-08-04 05:55 UTC, stuartc commented
@midigofrank excellent point, I don't want to get rid of 'scenario' style helpers... Perhaps there is a place to port these to use the factories, but live in a 'Scenarios' module - or something similar; don't want to hijack a generic name like that for just models/data.

So for now, I definitely don't have an issue with using those more complex fixtures. Happy to let the use cases settle and make a call when we have time or it's clearer.

2023-08-04 06:41 UTC, stuartc approved these changes

2023-08-04 06:43 UTC, merged